import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Next App
        </h1>

        <section>
          <div>jump to <Link href="/firstPage"><a className={styles.link}>First Page</a></Link></div>
          <div>jump to <Link href="/secondPage"><a className={styles.link}>Second Page</a></Link></div>
        </section>
      </main>
    </div>
  )
}

export default Home
